# theme: jekyll-theme-cayman
remote_theme: daattali/beautiful-jekyll
title: Puget Sound Repeater Roundabout
description: The weekend of November 19th, get to know our local repeaters!
author: Quentin K7DRQ
author_email: "k7drq@psrg.org"

navbar-links:
  Rules: "/"
  Participating Repeaters: "/repeaters"
  Log Sheet: "https://docs.google.com/spreadsheets/d/1n13bcPpxoyOSDa0yK9lEQ_deU9bA2bB2_maWWsNqK80/edit?usp=sharing"