# theme: jekyll-theme-cayman
remote_theme: daattali/beautiful-jekyll
title: Puget Sound Repeater Roundabout
description: The weekend of November 19th, get to know our local repeaters!

author: Quentin K7DRQ (k7drq@psrg.org)
author_email: "k7drq@psrg.org"

navbar-links:
  Rules: "/"
  Repeaters: "/repeaters"
  Map: "/map"
  Radio Files: "/files"
  Log Sheet: "https://docs.google.com/spreadsheets/d/1Frz6BoFUzWNTmiYED5OW_NTWhY-cSMRZQnhvdga4ORE/edit?usp=sharing"
  Submit Logs: "/submit_logs"
  Chat: "https://discord.gg/Hss7YNRj"

avatar: "/assets/images/logo.png"

gtag: "G-N7S873N5DC"

site-css:
  - assets/css/style.css
  - assets/css/spectrum.css
