# theme: jekyll-theme-cayman
remote_theme: daattali/beautiful-jekyll
title: Puget Sound Repeater Roundabout
description: The weekend of November 19th, make some noise on our local repeaters!

# navigation_header:
#   - title: Repeater Roundabout rules
#     url: /psrg_repeater_roundabout
#   - title: List of participating repeaters
#     url: /psrg_repeater_roundabout/repeaters
