# theme: jekyll-theme-cayman
remote_theme: daattali/beautiful-jekyll
title: Puget Sound Repeater Roundabout
description: The weekend of November 19th, get to know our local repeaters!

author: Quentin K7DRQ
author_email: "k7drq@psrg.org"

navbar-links:
  Rules: "/"
  Participating Repeaters: "/repeaters"
  Map: "/map"
  Chirp file: "https://raw.githubusercontent.com/QCaudron/repeater_roundabout/main/rr_frequencies.csv"
  Log Sheet: "https://docs.google.com/spreadsheets/d/1Frz6BoFUzWNTmiYED5OW_NTWhY-cSMRZQnhvdga4ORE/edit?usp=sharing"

avatar: "/assets/logo.png"
