# theme: jekyll-theme-cayman
remote_theme: daattali/beautiful-jekyll
title: Puget Sound Repeater Roundabout
description: The weekend of November 19th, make some noise on our local repeaters!
author:
  name: Quentin K7DRQ
  email: k7drq@psrg.org

navigation_header:
  - title: Repeater Roundabout rules
    url: /
  - List of participating repeaters
    url: /repeaters
