on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  verify_d878_line_endings:
    runs-on: ubuntu-latest
    steps:
      - run: python scripts/test_d878_line_endings.py
