on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify_d878_line_endings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Verify line endings
        run: python ./.github/test_crlf.py
