on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify_d878_line_endings:
    runs-on: ubuntu-latest
    steps:
      - name: Verify D878 line endings
        uses: actions/checkout@v2
        run: python ./.github/test_crlf.py
